name: Rubik's Cube Scramble Generator

on:
  push:
    paths:
      - "2026/python/01-18-rubiks-cube-scramble-generator.py"
  workflow_dispatch:
    inputs:
      moves_per_scramble:
        description: "Number of moves per scramble"
        required: false
        default: 20
      num_scrambles:
        description: "Number of scrambles"
        required: false
        default: 3
      moves_per_line:
        description: "Moves per line"
        required: false
        default: 5

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Run script
        run: |
          python 2026/01-18-rubiks-cube-scramble-generator.py
